{% set name = "legend-pygeom-l200" %}
{% set version = "0.2.0" %}
{% set python_min = "3.10" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/legend_pygeom_l200-{{ version }}.tar.gz
  sha256: 95e3cd42d8714f9ec37606ab9269b26b9d27f56a68f9ab2d553b2635292dd052

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  number: 0
  entry_points:
    - legend-pygeom-l200 = l200geom.cli:dump_gdml_cli

requirements:
  host:
    - python {{ python_min }}
    - setuptools >=61.2
    - setuptools-scm >=7
    - pip
  run:
    - python >={{ python_min }}
    - dbetto
    - legend-pygeom-hpges >=0.7.0
    - legend-pygeom-optics >=0.11
    - legend-pygeom-tools >=0.0.13
    - numpy
    - pint
    - pyg4ometry >=1.3.4
    - pylegendmeta >=v1.2.5
    - pyarrow
    - pyyaml
    - scipy
    - git

test:
  imports:
    - l200geom
  commands:
    - pip check
    - legend-pygeom-l200 --public-geom test.gdml
  requires:
    - python {{ python_min }}
    - pip

about:
  summary: Geometry model of the LEGEND-200 experimental setup
  home: https://github.com/legend-exp/legend-pygeom-l200
  license: GPL-3.0-only
  license_file: LICENSE
  doc_url: https://legend-pygeom-l200.readthedocs.io
  dev_url: https://github.com/legend-exp/legend-pygeom-l200

extra:
  recipe-maintainers:
    - gipert
    - ManuelHu
