{% set name = "legend-pygeom-l200" %}
{% set version = "0.3.1" %}
{% set python_min = "3.10" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/legend_pygeom_l200-{{ version }}.tar.gz
  sha256: dcfe66c8f166fc011027271af6d4c9f60a86fc239d6a8dd194bb293dad0c40fc

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  number: 0
  entry_points:
    - legend-pygeom-l200 = l200geom.cli:dump_gdml_cli

requirements:
  host:
    - python {{ python_min }}
    - setuptools >=61.2
    - setuptools-scm >=7
    - pip
  run:
    - gitpython
    - python >={{ python_min }}
    - dbetto
    - legend-pygeom-hpges >=0.7.0
    - legend-pygeom-optics >=0.13
    - legend-pygeom-tools >=0.0.18
    - numpy
    - pint
    - pyg4ometry >=1.3.4
    - pylegendmeta >=v1.2.5
    - pyarrow
    - pyyaml
    - scipy
    - git

test:
  imports:
    - l200geom
  commands:
    - pip check
    - legend-pygeom-l200 --public-geom test.gdml
  requires:
    - python {{ python_min }}
    - pip

about:
  summary: Geometry model of the LEGEND-200 experimental setup
  home: https://github.com/legend-exp/legend-pygeom-l200
  license: GPL-3.0-only
  license_file: LICENSE
  doc_url: https://legend-pygeom-l200.readthedocs.io
  dev_url: https://github.com/legend-exp/legend-pygeom-l200

extra:
  recipe-maintainers:
    - gipert
    - ManuelHu
