{% set name = "legend-pygeom-l200" %}
{% set version = "0.7.0" %}
{% set python_min = "3.10" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/legend_pygeom_l200-{{ version }}.tar.gz
  sha256: 92123cf14e776b765a42ad648031f27d94aaffede89607451f2dac830619e60f

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  number: 1
  entry_points:
    - legend-pygeom-l200 = pygeoml200.cli:dump_gdml_cli

requirements:
  host:
    - python {{ python_min }}
    - setuptools >=77
    - setuptools-scm >=7
    - pip
  run:
    - python >={{ python_min }}
    - dbetto
    - legend-pygeom-hpges >=0.9.0
    - legend-pygeom-optics >=0.15
    - legend-pygeom-tools >=0.0.25
    - numpy
    - pint
    - pyg4ometry >=1.3.4
    - pylegendmeta >=v1.3.1
    - pyyaml
    - scipy

test:
  imports:
    - l200geom
    - pygeoml200
  commands:
    - pip check
    - legend-pygeom-l200 --public-geom test.gdml
  requires:
    - python {{ python_min }}
    - pip

about:
  summary: Geometry model of the LEGEND-200 experimental setup
  home: https://github.com/legend-exp/legend-pygeom-l200
  license: GPL-3.0-only
  license_file: LICENSE
  doc_url: https://legend-pygeom-l200.readthedocs.io
  dev_url: https://github.com/legend-exp/legend-pygeom-l200

extra:
  recipe-maintainers:
    - gipert
    - ManuelHu
